import numpy as np
import rvo2
import json
import os
from pathlib import Path

from collections import defaultdict
import pysocialforce as psf

import matplotlib.animation as animation
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from matplotlib.patches import Circle

from controller import mpc_utils
from controller.group import grouping, draw_all_social_spaces

from sim.environment import Environment
from sim.metrics import *


class Simulator(object):
    # This class maintains the dataset based simulator
    # Each human in the simulator can follow the playback from the dataset (offline setting)
    # or only preserve the start and goals as they first appear/disappear
    # and use ORCA to drive them to the goals (online setting).

    def __init__(self, args, case_fpath, logger):
        # case_fpath is the json file path to the test cases
        # please run test_case_generation.py to generate test cases first

        self.output_dir = args.output_dir

        # preload datasets
        self.logger = logger
        self.envs = Environment(args.fps, args.dset_path, logger)
        self.envs.preload_data(args.envs)

        # simulator parameters, which can be set by config file
        self.dt = args.dt
        self.robot_speed = args.max_speed
        self.differential = args.differential
        self.collision_radius = args.collision_radius
        self.goal_radius = args.goal_radius
        self.time_horizon = args.time_horizon
        self.use_a_omega = args.use_a_omega

        # simulator options, which can be set by command line args
        self.react = args.react # for if using orca to simulata or use ground truth trajs
        self.animate = args.animate # for if saving the render frames to video during simulation

        self.case_id = None

        self.exp_name = args.exp_name.split('_')[-1]
        print("------ exp name:", self.exp_name)
        
        # for crowd follow debugging
        self.follow_pos = None
        self.follow_vel = None

        self.max_label = None

        self.logger.info("Simulator initialized.")
        self.logger.info("React: {}".format(self.react))
        self.logger.info("Animate: {}".format(self.animate))
        
        self.obs_history = []

        self.done = False

        self.follow_weight = args.follow_weight

        self._load_cases(case_fpath)
        self.reset_cases()

        return

    def _load_cases(self, case_fpath):
        # load the test cases from the json file
        # the test cases are generated by test_case_generation.py
        # the test cases are a list of dictionaries, each dictionary contains the
        # environment name, environment flag, start position, end position, start frame, and time limit

        with open(case_fpath, 'r') as f:
            self.case_list = json.load(f)

        self.case_pt = 0
        return

    def reset_cases(self):
        # shuffle the cases

        self.case_id_list = np.arange(len(self.case_list))
        # np.random.shuffle(self.case_id_list)
        self.case_pt = 0
        return

    def _init_group_params(self):
        # initialize the group parameters
        is_dense_env1 = (self.env_name == "ucy" and self.env_flag == 2)
        if is_dense_env1:
            self.group_params = {
                "size_const": 0.25,
                "pos_threshold": 1.5,
                "th_threshold": 15 / 180.0 * np.pi,
                "spd_threshold": 0.5,
                "spd_ignore": 0.5,  # consider as static if < 0.5 m/s
            }
        else:
            self.group_params = {
                "size_const": 0.35,
                "pos_threshold": 2.0,
                "th_threshold": 30 / 180.0 * np.pi,
                "spd_threshold": 1.0,
                "spd_ignore": 0.5,
            }
        return

    def dataset_history(self, ped_idx, new_pedestrians_idx=None):
        # return the position and velocity history of a pedestrian
        # if the pedestrian is not in the dataset, return None

        if new_pedestrians_idx is None:
            if ped_idx not in self.pedestrians_idx:
                return [], []
        else:
            if ped_idx not in new_pedestrians_idx:
                return [], []

        pos_history = []
        vel_history = []
        for i in range(self.time - self.history_steps, self.time):
            if (i < 0) or (ped_idx not in self.env.video_pedidx_matrix[i]):
                start_frame = self.env.people_start_frame[ped_idx]
                start_pos = np.array(self.env.people_coords_complete[ped_idx][0])
                start_vel = np.array(self.env.people_velocity_complete[ped_idx][0])
                pos = start_pos - start_vel * (start_frame - i) * self.dt
                vel = start_vel
            else:
                ped_id = self.env.video_pedidx_matrix[i].index(ped_idx)
                pos = self.env.video_position_matrix[i][ped_id]
                vel = self.env.video_velocity_matrix[i][ped_id]
            pos_history.append(pos)
            vel_history.append(vel)

        return pos_history, vel_history

    def _update_from_dataset(self):
        # update the pedestrian attributes from the dataset
        self.pedestrians_pos = self.env.video_position_matrix[self.time]
        self.pedestrians_vel = self.env.video_velocity_matrix[self.time]
        self.pedestrians_idx = self.env.video_pedidx_matrix[self.time]
        self.pedestrians_goal = []
        for ped_idx in self.pedestrians_idx:
            self.pedestrians_goal.append(self.env.people_coords_complete[ped_idx][-1])

        self.pedestrians_pos_history = []
        self.pedestrians_vel_history = []
                
        return

    def _group_observations(self):
        # group the observations
        # Note: the history positions and velocities are not grouped
        if len(self.pedestrians_pos) == 0:
            self.group_labels = []
        else:
            self.group_labels = grouping(self.pedestrians_pos, self.pedestrians_vel, self.group_params)
        return

    def _extract_observation(self, observation_dict):
        # Extract information from observation dictionary that is useful to record
        # Useful is defined as needed for evaluation after the trail ends

        record_dict = {}
        record_dict['success'] = observation_dict['success']
        record_dict['num_pedestrians'] = observation_dict['num_pedestrians']
        record_dict['robot_pos'] = observation_dict['robot_pos']
        record_dict['robot_vel'] = observation_dict['robot_vel']
        record_dict['robot_th'] = observation_dict['robot_th']
        record_dict['pedestrians_pos'] = observation_dict['pedestrians_pos']
        record_dict['pedestrians_vel'] = observation_dict['pedestrians_vel']
        record_dict['pedestrians_idx'] = observation_dict['pedestrians_idx']
        record_dict['pedestrians_goal'] = observation_dict['pedestrians_goal']
        record_dict['group_labels'] = observation_dict['group_labels']
        return record_dict

    def _get_observation_dict(self, success):
        # get the observation dictionary

        observation_dict = {}
        observation_dict['success'] = success
        observation_dict['num_pedestrians'] = self.num_ped
        observation_dict['robot_pos'] = self.robot_pos
        observation_dict['robot_vel'] = self.robot_vel
        observation_dict['robot_th'] = self.robot_th
        observation_dict['robot_goal'] = self.goal_pos
        observation_dict['pedestrians_pos'] = np.array(self.pedestrians_pos)
        observation_dict['pedestrians_vel'] = np.array(self.pedestrians_vel)
        observation_dict['pedestrians_idx'] = np.array(self.pedestrians_idx)
        observation_dict['pedestrians_pos_history'] = np.array(self.pedestrians_pos_history)
        observation_dict['pedestrians_vel_history'] = np.array(self.pedestrians_vel_history)
        observation_dict['pedestrians_goal'] = np.array(self.pedestrians_goal)
        observation_dict['group_labels'] = np.array(self.group_labels)

        return observation_dict

    def reset(self, case_id=None):

        self.case_id = case_id

        # reset the environment
        # if case_id is None, then select the next case from the list
        if case_id is None:
            case = self.case_list[self.case_id_list[self.case_pt]]
            self.case_pt += 1
            if self.case_pt >= len(self.case_list):
                self.reset_cases()
        else:
            case = self.case_list[case_id]

        # env is (env_name, env_flag)
        self.env_name = case['env']
        self.env_flag = case['env_flag']

        # clean the folder figs
        if self.animate:
            figs_dir = f"{self.output_dir}/figs/{self.env_name}_{self.env_flag}/case_{self.case_id}"
            if not os.path.exists(figs_dir):
                os.makedirs(figs_dir)
            else:
                for f in os.listdir(figs_dir):
                    os.remove(os.path.join(figs_dir, f))

        self.start_pos = case['start_pos']
        self.goal_pos = case['end_pos']
        
        self.start_frame = case['start_frame']
        self.time_limit = self.start_frame + 3 * case['time_limit']

        self.env = self.envs.select_env((self.env_name, self.env_flag))
        self._init_group_params()

        self.time = self.start_frame
        self.robot_pos = np.array(self.start_pos)

        # by default, the robot faces the goal
        self.robot_th = np.arctan2(self.goal_pos[1] - self.robot_pos[1], self.goal_pos[0] - self.robot_pos[0]) # robot heading orientation
        self.robot_vel = np.array([0, self.robot_th]) # robot_vel here means robot status (v, theta) # change to 0.5 for speed when step_only_sfm
        # self.robot_vel = np.array([0.5, self.robot_th]) # robot_vel here means robot status (v, theta) # change to 0.5 for speed when step_only_sfm
        self.robot_path = np.array([self.robot_pos])

        # For saving the robot path and human path
        self.save_all_traj = []

        # get the pedestrian properties
        self._update_from_dataset()
        self.num_ped = len(self.pedestrians_idx)

        if self.react:
            self.history_idxes = self.pedestrians_idx.copy() # keep track of which pedestrians have showed up

        self._group_observations()

        # return the initial observation
        observation_dict = self._get_observation_dict(False)

        record_dict = self._extract_observation(observation_dict)
        self.obs_history = [record_dict]

        if self.animate:
            self.fig, self.ax = plt.subplots()
            self.ax.set_aspect(1)
            self.image_sequences = []
            frame = self.render_v2()      # will use self.ax
            self.image_sequences.append(frame)


        self.fail_reason = None

        self.done = False

        return observation_dict

    def get_latest_render_frame(self):
        # get the latest render frame
        if len(self.image_sequences) == 0:
            return None
        return self.image_sequences[-1]
    
    def update_latest_render_frame(self, frame):
        # update the latest render frame
        self.image_sequences[-1] = frame
        return

    def _get_pref_velocity(self, pos, goal, spd_limit):
        # get the preferred velocity of a pedestrian
        #
        # pos is the current position
        # goal is the goal position
        # spd_limit is the speed limit

        vel = np.array(goal) - np.array(pos)
        dist = np.linalg.norm(vel)
        if not (dist < self.goal_radius):
            vel = vel / np.linalg.norm(vel) * spd_limit
        else:
            vel = [0, 0]
        return (vel[0], vel[1])

    def rvo_step(self, robo_curr, ped_pos, ped_vel, ped_goals, if_return_robot=False):
        # robo_curr is the current robot position
        # robo_goal is the robot goal position
        # dt is the time step
        # robo_max_v is the robot maximum velocity
        # t_horizon is the time horizon
        # ped_pos is the pedestrian positions
        # ped_vel is the pedestrian velocities
        # ped_goals is the pedestrian goals

        robo_goal = np.array(self.goal_pos)
        dt = self.dt
        t_horizon = self.time_horizon
        robo_max_v = self.robot_speed
        # setting pedestrian max speed to robot max speed
        ped_max_spd = robo_max_v

        # initialize the simulator
        # RVOSimulator(float timeStep, float neighborDist, size_t maxNeighbors, float timeHorizon, float timeHorizonObst, float radius, float maxSpeed)
        sim = rvo2.PyRVOSimulator(dt, 2.5, 10, t_horizon, 2, 0.5, ped_max_spd)

        # add the robot
        robot = sim.addAgent((robo_curr[0], robo_curr[1]))
        sim.setAgentMaxSpeed(robot, robo_max_v)
        sim.setAgentPrefVelocity(robot, self._get_pref_velocity(robo_curr, robo_goal, robo_max_v))

        # add the pedestrians
        num_ped = len(ped_pos)
        ped_list = []
        for i in range(num_ped):
            ped = sim.addAgent((ped_pos[i][0], ped_pos[i][1]))
            ped_spd = np.linalg.norm(np.array(ped_vel[i]))
            sim.setAgentVelocity(ped, (ped_vel[i][0], ped_vel[i][1]))
            sim.setAgentMaxSpeed(ped, max(ped_spd, ped_max_spd))
            sim.setAgentPrefVelocity(ped, self._get_pref_velocity(ped_pos[i], ped_goals[i], ped_max_spd))
            ped_list.append(ped)

        sim.doStep()

        ped_pos_new = np.array([sim.getAgentPosition(ped) for ped in ped_list])
        ped_vel_new = np.array([sim.getAgentVelocity(ped) for ped in ped_list])

        if if_return_robot:
            robot_pos_new = sim.getAgentPosition(robot)
            robot_vel_new = sim.getAgentVelocity(robot)

            vx = robot_vel_new[0]
            vy = robot_vel_new[1]
            action_speed = float(np.hypot(vx, vy))
            
            theta_des = np.arctan2(vy, vx)
            theta_cur = self.robot_th
            angle_err = theta_des - theta_cur
            
            k_w = 1.0
            w_max = 3.14

            if abs(angle_err) > np.pi / 2:
                self.robot_th = self.robot_th + np.pi if self.robot_th <= 0 else self.robot_th - np.pi
                angle_err = theta_des - self.robot_th

            action_theta = float(np.clip(k_w * angle_err, -w_max, w_max))
            
            displacement = self.get_dynamics(action_speed, action_theta, self.robot_th)
            
            robot_pos_new = self.robot_pos + displacement
            robot_new_theta = mpc_utils.wrap_to_pi(self.robot_th + action_theta * self.dt)
            
            robot_vel_new = np.array([action_speed, robot_new_theta]) # (v, theta)

            return ped_pos_new, ped_vel_new, robot_pos_new, robot_vel_new

        return ped_pos_new, ped_vel_new

    def sfm_step(self, old_robot_pos, old_robot_vx_vy, ped_pos, ped_vel, ped_goals, group_labels, if_return_robot=False):
        if len(ped_pos) == 0:  # Check if there are no pedestrians
            ped_pos_new = np.empty((0, 2))  # Shape (0, 2)
            ped_vel_new = np.empty((0, 2))  # Shape (0, 2)
            
            if if_return_robot:
                robot_pos_new = np.array([old_robot_pos[0] + old_robot_vx_vy[0] * self.dt,
                                        old_robot_pos[1] + old_robot_vx_vy[1] * self.dt])
                robot_vel_new = np.array(old_robot_vx_vy)  # (vx, vy)
                return ped_pos_new, ped_vel_new, robot_pos_new, robot_vel_new

            return ped_pos_new, ped_vel_new

        ped_pos = np.array(ped_pos).reshape(-1, 2)  # Shape (num_pedestrians, 2) (px,py)
        ped_vel = np.array(ped_vel).reshape(-1, 2)  # Shape (num_pedestrians, 2) (vx,vy)
        ped_goals = np.array(ped_goals).reshape(-1, 2)  # Shape (num_pedestrians, 2) (gx,gy)
        ped_data = np.column_stack((ped_pos, ped_vel, ped_goals))
        robot_data = np.array([old_robot_pos[0], old_robot_pos[1], old_robot_vx_vy[0], old_robot_vx_vy[1], self.goal_pos[0], self.goal_pos[1]]).reshape(1, -1)

        combined_data = np.vstack((ped_data, robot_data))

        group_dict = defaultdict(list)

        for idx, label in enumerate(group_labels):
            group_dict[label].append(idx)

        if self.max_label is not None:
            group_dict[self.max_label].append(len(combined_data) - 1)

        grouped_indices = list(group_dict.values())
        sfm_config_file = Path(__file__).resolve().parent.parent.joinpath("sfm_config.toml")
        sim = psf.Simulator(combined_data, groups=grouped_indices, obstacles=None, config_file=sfm_config_file)
        sim.step()

        ped_data_all_steps, _ = sim.get_states()
        ped_data_new = ped_data_all_steps[1]
        ped_pos_new = ped_data_new[:-1, :2]
        ped_vel_new = ped_data_new[:-1, 2:4] # (vx, vy)
        
        if if_return_robot:
            robot_pos_new = ped_data_new[-1, :2]
            robot_vel_new = ped_data_new[-1, 2:4]

            return ped_pos_new, ped_vel_new, robot_pos_new, robot_vel_new

        return ped_pos_new, ped_vel_new

    def get_dynamics(self, v, w, th):
        if w == 0 or not self.differential:
            displacement = np.array([
                v * np.cos(th) * self.dt,
                v * np.sin(th) * self.dt
            ])
        else:
            displacement = np.array([
                v/w * (np.sin(th + w * self.dt) - np.sin(th)),
                -v/w * (np.cos(th + w * self.dt) - np.cos(th))
            ])

        return displacement

    def step(self, action, follow_state=None):

        ##### save the robot path and human path #####
        self.save_all_traj.append({
            "time": self.time,
            "robot_pos": self.robot_pos.copy(),
            "pedestrians_pos": np.array(self.pedestrians_pos).copy(),
            "pedestrians_vel": np.array(self.pedestrians_vel).copy()
        })
        ##############################################

        reward = 0

        if follow_state is not None:
            follow_pos = follow_state[0, :2].copy()
            self.follow_pos = follow_pos

        if self.done:
            raise ValueError("Environment is done. Please reset.")

        # update time
        self.time += 1

        # update robot position
        old_robot_pos = self.robot_pos.copy()
        old_robot_vx_vy = (self.robot_vel[0] * np.cos(self.robot_th), self.robot_vel[0] * np.sin(self.robot_th))

        if self.use_a_omega: # use a, w as the controller output action
            a, w = action[0], action[1]
            v, th = self.robot_vel[0], self.robot_th
            displacement = self.get_dynamics(v, w, th)
            v += a * self.dt
        else: # use v omega. use v, w as the controller output action
            v, th = action[0], self.robot_th
            w = action[1]
            displacement = self.get_dynamics(v, w, th)
        self.robot_pos = self.robot_pos + displacement
        th = mpc_utils.wrap_to_pi(th + w * self.dt)
        # th = mpc_utils.wrapTo2pi(th + w * self.dt)
        self.robot_vel = np.array([v, th]) # set robot_vel to [v, theta]
        self.robot_th = th

        self.robot_path = np.append(self.robot_path, [self.robot_pos], axis=0)

        # update pedestrian positions
        if self.time > self.env.total_num_frames:
        # if self.time > self.time_limit:
            # no more pedestrian data, so simulator is empty
            self.pedestrians_pos = []
            self.pedestrians_vel = []
            self.pedestrians_idx = []
            self.pedestrians_pos_history = []
            self.pedestrians_vel_history = []
            self.pedestrians_goal = []
        else:
            if self.react:
                ###### use ORCA to update pedestrian positions ######
                tmp_pedestrians_pos, tmp_pedestrians_vel = self.rvo_step(
                    old_robot_pos, self.pedestrians_pos, self.pedestrians_vel, self.pedestrians_goal)
                ###### or SFM ######
                # tmp_pedestrians_pos, tmp_pedestrians_vel = self.sfm_step(
                #     old_robot_pos, old_robot_vx_vy, self.pedestrians_pos, self.pedestrians_vel, self.pedestrians_goal, self.group_labels)

                tmp_pedestrians_idx = self.pedestrians_idx
                # remove pedestrians that have reached their goals
                new_pedestrians_idx = []
                new_pedestrians_pos = []
                new_pedestrians_vel = []
                new_pedestrians_pos_history = []
                new_pedestrians_vel_history = []
                new_pedestrians_goal = []
                for i in range(len(tmp_pedestrians_pos)):
                    if np.linalg.norm(tmp_pedestrians_pos[i] - self.pedestrians_goal[i]) > self.goal_radius:
                        new_pedestrians_idx.append(tmp_pedestrians_idx[i])
                        new_pedestrians_pos.append(tmp_pedestrians_pos[i])
                        new_pedestrians_vel.append(tmp_pedestrians_vel[i])
                        new_pedestrians_goal.append(self.pedestrians_goal[i])

                # add new pedestrians
                current_pedestrians_idx = self.env.video_pedidx_matrix[self.time]
                for i in range(len(current_pedestrians_idx)):
                    if current_pedestrians_idx[i] not in self.history_idxes:
                        #### if human appear location is too close to robot, dont add ####
                        appear_distance = np.linalg.norm(old_robot_pos - self.env.video_position_matrix[self.time][i])
                        if appear_distance < self.collision_radius + 0.5:
                            continue
                    
                        self.history_idxes.append(current_pedestrians_idx[i])
                        new_pedestrians_idx.append(current_pedestrians_idx[i])
                        new_pedestrians_pos.append(self.env.video_position_matrix[self.time][i])
                        new_pedestrians_vel.append(self.env.video_velocity_matrix[self.time][i])

                        new_pedestrians_goal.append(self.env.people_coords_complete[current_pedestrians_idx[i]][-1])

                # update the pedestrian properties
                self.pedestrians_idx = new_pedestrians_idx
                self.pedestrians_pos = new_pedestrians_pos
                self.pedestrians_vel = new_pedestrians_vel
                self.pedestrians_pos_history = new_pedestrians_pos_history
                self.pedestrians_vel_history = new_pedestrians_vel_history
                self.pedestrians_goal = new_pedestrians_goal
            else:
                # use dataset to update pedestrian positions
                self._update_from_dataset()

        success = False
        reach_goal_reward = 0
        self.done = False
        self.num_ped = len(self.pedestrians_idx)

        # check if the episode is done
        if self.time >= self.time_limit:
            self.done = True
            self.fail_reason = "Time"
            self.logger.info("Time limit exceeded. Terminating episode.")
        elif (self.num_ped > 0) and (np.min(np.linalg.norm(self.robot_pos - np.array(self.pedestrians_pos), axis=1)) < self.collision_radius):
            success = False
            # self.done = True
            self.done = False
            self.fail_reason = "Collision"
            self.logger.info("Collision detected. Terminating episode.")
        elif np.linalg.norm(self.robot_pos - self.goal_pos) < self.goal_radius:
            reach_goal_reward = 1
            success = True
            self.done = True
            self.logger.info("----------------Goal reached----------------")

        self._group_observations()

        # update the observation
        observation_dict = self._get_observation_dict(success)

        record_dict = self._extract_observation(observation_dict)
        self.obs_history.append(record_dict)

        if self.animate:
            frame = self.render_v2()
            self.image_sequences.append(frame)
            ########### save the image to the output directory ##############
            # if self.time % 20 == 0:
            #     self.fig.canvas.draw()   # draw() (not draw_idle)
            #     for arts in self.image_sequences[:-1]:
            #         for a in arts:
            #             a.set_visible(False)
            #     # show current frame
            #     for a in self.image_sequences[-1]:
            #         a.set_visible(True)
            #     self.fig.savefig(f"{self.output_dir}/figs/{self.env_name}_{self.env_flag}/case_{self.case_id}/{self.time}.png")
            #################################################################
            if self.done:
                self._write_video()

        # compute the reward
        ## reward for reaching the goal with range: [-1, 1]
        reach_goal_reward_dense = np.linalg.norm(old_robot_pos - self.goal_pos) - np.linalg.norm(self.robot_pos - self.goal_pos)
        ## reward to getting closer to the goal with range: [0, 1]
        group_matching_score = self.get_group_score(observation_dict)
        group_matching_reward = group_matching_score

        reward += 100 * reach_goal_reward
        reward += 1 * reach_goal_reward_dense
        reward += self.follow_weight * group_matching_reward

        info_dict = {
            "reach_goal_reward": reach_goal_reward,
            "reach_goal_reward_dense": reach_goal_reward_dense,
            "group_matching_reward": group_matching_reward,}

        # return the observation, reward(not used), done, and info
        return observation_dict, reward, self.done, success, self.time, info_dict

    def step_only_orca(self):

        ##### save the robot path and human path #####
        self.save_all_traj.append({
            "time": self.time,
            "robot_pos": self.robot_pos.copy(),
            "pedestrians_pos": np.array(self.pedestrians_pos).copy(),
            "pedestrians_vel": np.array(self.pedestrians_vel).copy()
        })
        ##############################################

        reward = 0

        if self.done:
            raise ValueError("Environment is done. Please reset.")

        # update time
        self.time += 1

        # update robot position
        old_robot_pos = self.robot_pos.copy()
        old_robot_vx_vy = (self.robot_vel[0] * np.cos(self.robot_th), self.robot_vel[0] * np.sin(self.robot_th))

        # update pedestrian positions
        if self.time > self.env.total_num_frames:
            # no more pedestrian data, so simulator is empty
            self.pedestrians_pos = []
            self.pedestrians_vel = []
            self.pedestrians_idx = []
            self.pedestrians_pos_history = []
            self.pedestrians_vel_history = []
            self.pedestrians_goal = []
            
            _, _, new_robot_pos, new_robot_vel = self.rvo_step(
                old_robot_pos, self.pedestrians_pos, self.pedestrians_vel, self.pedestrians_goal, if_return_robot=True)
            
        else:            
            if self.react:
                tmp_pedestrians_pos, tmp_pedestrians_vel = self.rvo_step(
                    old_robot_pos, self.pedestrians_pos, self.pedestrians_vel, self.pedestrians_goal)

                _, _, new_robot_pos, new_robot_vel = self.rvo_step(
                    old_robot_pos, self.pedestrians_pos, self.pedestrians_vel, self.pedestrians_goal, if_return_robot=True)

                tmp_pedestrians_idx = self.pedestrians_idx
                
                # remove pedestrians that have reached their goals
                new_pedestrians_idx = []
                new_pedestrians_pos = []
                new_pedestrians_vel = []
                new_pedestrians_pos_history = []
                new_pedestrians_vel_history = []
                new_pedestrians_goal = []
                for i in range(len(tmp_pedestrians_pos)):
                    if np.linalg.norm(tmp_pedestrians_pos[i] - self.pedestrians_goal[i]) > self.goal_radius:
                        new_pedestrians_idx.append(tmp_pedestrians_idx[i])
                        new_pedestrians_pos.append(tmp_pedestrians_pos[i])
                        new_pedestrians_vel.append(tmp_pedestrians_vel[i])

                        new_pedestrians_goal.append(self.pedestrians_goal[i])

                # add new pedestrians
                current_pedestrians_idx = self.env.video_pedidx_matrix[self.time]
                for i in range(len(current_pedestrians_idx)):
                    if current_pedestrians_idx[i] not in self.history_idxes:
                        #### if human appear location is too close to robot, dont add ####
                        appear_distance = np.linalg.norm(old_robot_pos - self.env.video_position_matrix[self.time][i])
                        if appear_distance < self.collision_radius + 0.5:
                            continue

                        self.history_idxes.append(current_pedestrians_idx[i])
                        new_pedestrians_idx.append(current_pedestrians_idx[i])
                        new_pedestrians_pos.append(self.env.video_position_matrix[self.time][i])
                        new_pedestrians_vel.append(self.env.video_velocity_matrix[self.time][i])
                        new_pedestrians_goal.append(self.env.people_coords_complete[current_pedestrians_idx[i]][-1])

                # update the pedestrian properties
                self.pedestrians_idx = new_pedestrians_idx
                self.pedestrians_pos = new_pedestrians_pos
                self.pedestrians_vel = new_pedestrians_vel
                self.pedestrians_pos_history = new_pedestrians_pos_history
                self.pedestrians_vel_history = new_pedestrians_vel_history
                self.pedestrians_goal = new_pedestrians_goal
            else:
                _, _, new_robot_pos, new_robot_vel = self.rvo_step(
                    old_robot_pos, self.pedestrians_pos, self.pedestrians_vel, self.pedestrians_goal, if_return_robot=True)
                # use dataset to update pedestrian positions
                self._update_from_dataset()
        
        self.robot_pos = np.array(new_robot_pos)
        new_robot_theta = new_robot_vel[1]
        new_robot_speed = new_robot_vel[0]
        self.robot_vel = np.array([new_robot_speed, new_robot_theta]) # set robot_vel to [v, theta]
        self.robot_th = new_robot_theta

        self.robot_path = np.append(self.robot_path, [self.robot_pos], axis=0)

        success = False
        self.done = False
        self.num_ped = len(self.pedestrians_idx)

        # check if the episode is done
        if self.time >= self.time_limit:
            self.done = True
            self.fail_reason = "Time"
            self.logger.info("Time limit exceeded. Terminating episode.")
        elif (self.num_ped > 0) and (np.min(np.linalg.norm(self.robot_pos - np.array(self.pedestrians_pos), axis=1)) < self.collision_radius):
            success = False
            # self.done = True
            self.done = False
            self.fail_reason = "Collision"
            self.logger.info("Collision detected. Terminating episode.")
        elif np.linalg.norm(self.robot_pos - self.goal_pos) < self.goal_radius:
            success = True
            self.done = True
            self.logger.info("----------------Goal reached----------------")

        self._group_observations()

        # update the observation
        observation_dict = self._get_observation_dict(success)

        record_dict = self._extract_observation(observation_dict)
        self.obs_history.append(record_dict)

        if self.animate:
            frame = self.render_v2()
            self.image_sequences.append(frame)
            ########### save the image to the output directory ##############
            # if self.time % 5 == 0:
            #     tmp_fig = plt.figure()
            #     tmp_ax = tmp_fig.add_subplot(111)
            #     self.render_v2(tmp_ax)
            #     tmp_fig.savefig(f"{self.output_dir}/figs/{self.env_name}_{self.env_flag}/case_{self.case_id}/{self.time}.png")
            #     plt.close(tmp_fig)
            #################################################################
            if self.done:
                self._write_video()

        info_dict = {}

        # return the observation, reward(not used), done, and info
        return observation_dict, reward, self.done, success, self.time, info_dict

    def step_only_sfm(self):

        ##### save the robot path and human path #####
        self.save_all_traj.append({
            "time": self.time,
            "robot_pos": self.robot_pos.copy(),
            "pedestrians_pos": np.array(self.pedestrians_pos).copy(),
            "pedestrians_vel": np.array(self.pedestrians_vel).copy()
        })
        ##############################################

        reward = 0
        
        if self.done:
            raise ValueError("Environment is done. Please reset.")

        # update time
        self.time += 1

        # update robot position
        old_robot_pos = self.robot_pos.copy()
        old_robot_vx_vy = (self.robot_vel[0] * np.cos(self.robot_th), self.robot_vel[0] * np.sin(self.robot_th))

        # update pedestrian positions
        if self.time > self.env.total_num_frames:
            # no more pedestrian data, so simulator is empty
            self.pedestrians_pos = []
            self.pedestrians_vel = []
            self.pedestrians_idx = []
            self.pedestrians_pos_history = []
            self.pedestrians_vel_history = []
            self.pedestrians_goal = []
            
            _, _, new_robot_pos, new_robot_vel = self.sfm_step(
                old_robot_pos, old_robot_vx_vy, self.pedestrians_pos, self.pedestrians_vel, self.pedestrians_goal, self.group_labels, if_return_robot=True)
        
        else:
            if self.react:
                tmp_pedestrians_pos, tmp_pedestrians_vel = self.sfm_step(
                    old_robot_pos, old_robot_vx_vy, self.pedestrians_pos, self.pedestrians_vel, self.pedestrians_goal, self.group_labels)
                _, _, new_robot_pos, new_robot_vel = self.sfm_step(
                    old_robot_pos, old_robot_vx_vy, self.pedestrians_pos, self.pedestrians_vel, self.pedestrians_goal, self.group_labels, if_return_robot=True)

                tmp_pedestrians_idx = self.pedestrians_idx
                # remove pedestrians that have reached their goals
                new_pedestrians_idx = []
                new_pedestrians_pos = []
                new_pedestrians_vel = []
                new_pedestrians_pos_history = []
                new_pedestrians_vel_history = []
                new_pedestrians_goal = []
                for i in range(len(tmp_pedestrians_pos)):
                    if np.linalg.norm(tmp_pedestrians_pos[i] - self.pedestrians_goal[i]) > self.goal_radius:
                        new_pedestrians_idx.append(tmp_pedestrians_idx[i])
                        new_pedestrians_pos.append(tmp_pedestrians_pos[i])
                        new_pedestrians_vel.append(tmp_pedestrians_vel[i])
                        new_pedestrians_goal.append(self.pedestrians_goal[i])

                # add new pedestrians
                current_pedestrians_idx = self.env.video_pedidx_matrix[self.time]
                for i in range(len(current_pedestrians_idx)):
                    if current_pedestrians_idx[i] not in self.history_idxes:
                        #### if human appear location is too close to robot, dont add ####
                        appear_distance = np.linalg.norm(old_robot_pos - self.env.video_position_matrix[self.time][i])
                        if appear_distance < self.collision_radius + 0.5:
                            continue

                        self.history_idxes.append(current_pedestrians_idx[i])
                        new_pedestrians_idx.append(current_pedestrians_idx[i])
                        new_pedestrians_pos.append(self.env.video_position_matrix[self.time][i])
                        new_pedestrians_vel.append(self.env.video_velocity_matrix[self.time][i])
                        new_pedestrians_goal.append(self.env.people_coords_complete[current_pedestrians_idx[i]][-1])

                # update the pedestrian properties
                self.pedestrians_idx = new_pedestrians_idx
                self.pedestrians_pos = new_pedestrians_pos
                self.pedestrians_vel = new_pedestrians_vel
                self.pedestrians_pos_history = new_pedestrians_pos_history
                self.pedestrians_vel_history = new_pedestrians_vel_history
                self.pedestrians_goal = new_pedestrians_goal
            else:
                _, _, new_robot_pos, new_robot_vel = self.sfm_step(
                    old_robot_pos, old_robot_vx_vy, self.pedestrians_pos, self.pedestrians_vel, self.pedestrians_goal, self.group_labels, if_return_robot=True)
                # use dataset to update pedestrian positions
                self._update_from_dataset()

        self.robot_pos = new_robot_pos
        new_robot_theta = np.arctan2(new_robot_vel[1], new_robot_vel[0])
        new_robot_speed = np.linalg.norm(new_robot_vel)
        self.robot_vel = np.array([new_robot_speed, new_robot_theta]) # set robot_vel to [v, theta]
        self.robot_th = new_robot_theta

        self.robot_path = np.append(self.robot_path, [self.robot_pos], axis=0)

        success = False
        self.done = False
        self.num_ped = len(self.pedestrians_idx)

        # check if the episode is done
        if self.time >= self.time_limit:
            self.done = True
            self.fail_reason = "Time"
            self.logger.info("Time limit exceeded. Terminating episode.")
        elif (self.num_ped > 0) and (np.min(np.linalg.norm(self.robot_pos - np.array(self.pedestrians_pos), axis=1)) < self.collision_radius):
            success = False
            self.done = True
            self.fail_reason = "Collision"
            self.logger.info("Collision detected. Terminating episode.")
        elif np.linalg.norm(self.robot_pos - self.goal_pos) < self.goal_radius:
            success = True
            self.done = True
            self.logger.info("----------------Goal reached----------------")

        self._group_observations()

        # update the observation
        observation_dict = self._get_observation_dict(success)

        record_dict = self._extract_observation(observation_dict)
        self.obs_history.append(record_dict)

        if self.animate:
            frame = self.render_v2()
            self.image_sequences.append(frame)
            ########### save the image to the output directory ##############
            # if self.time % 20 == 0:
            #     tmp_fig = plt.figure()
            #     tmp_ax = tmp_fig.add_subplot(111)
            #     self.render_v2(tmp_ax)
            #     tmp_fig.savefig(f"{self.output_dir}/figs/{self.env_name}_{self.env_flag}/case_{self.case_id}/{self.time}.png")
            #     plt.close(tmp_fig)
            #################################################################
            if self.done:
                self._write_video()

        info_dict = {}

        # return the observation, reward(not used), done, and info
        return observation_dict, reward, self.done, success, self.time, info_dict

    def get_group_score(self, obs):
        group_data = defaultdict(list)

        for i, label in enumerate(obs["group_labels"]):
            group_data[label].append((obs["pedestrians_pos"][i], obs["pedestrians_vel"][i]))

        group_scores = {}

        if len(group_data) == 0:
            return 0

        for label, members in group_data.items():
            positions = np.array([m[0] for m in members])

            distances = np.linalg.norm(positions - self.robot_pos, axis=1)
            distance_to_group = np.min(distances)

            velocities = np.array([m[1] for m in members])
            speed = np.linalg.norm(velocities, axis=1)
            motion_angle = np.mod(np.arctan2(velocities[:, 1], velocities[:, 0]), 2 * np.pi)
            avg_speed = np.mean(speed)
            avg_motion_angle = mpc_utils.circmean(motion_angle, np.ones(len(motion_angle)))

            angle_diff = mpc_utils.circdiff(avg_motion_angle, self.robot_vel[1])
            speed_diff = np.abs(avg_speed - self.robot_vel[0])

            sigma_speed = 0.5
            sigma_angle = 15 / 180 * np.pi

            speed_score = np.exp(- (speed_diff / sigma_speed) ** 2)
            angle_score = np.exp(- (angle_diff / sigma_angle) ** 2)

            distance_score = np.exp(- (distance_to_group) ** 2)

            group_scores[label] = speed_score * angle_score * distance_score

        # max_group_score = max(group_scores.values())
        self.max_label, max_group_score = max(group_scores.items(), key=lambda item: item[1])

        if max_group_score == 0:
            self.max_label = None

        return max_group_score


    def get_case_info(self):
        # get the environment information
        case_info = {}
        case_info['env_name'] = self.env_name
        case_info['env_flag'] = self.env_flag
        case_info['start_pos'] = self.start_pos
        case_info['goal_pos'] = self.goal_pos
        case_info['start_frame'] = self.start_frame
        case_info['time_limit'] = self.time_limit
        return case_info
    

    def evaluate(self, output=False):
        # evaluate the results of the simulation trial
        # can evaluate in the middle of a trial, but a warning will show up

        result_dict = {}

        if len(self.obs_history) == 0:
            self.logger.warning("No data to evaluate.")
            return result_dict

        if not self.done:
            self.logger.warning("Simulation of this trial is not finished.")

        # Is the trial a success
        result_dict['success'] = self.obs_history[-1]['success']
        result_dict['fail_reason'] = self.fail_reason
        result_dict['navigation_time'] = (self.time - self.start_frame) * self.dt
        result_dict['path_length'] = get_path_length(self.robot_path)
        result_dict['path_smoothness'] = get_path_smoothness(self.robot_path)
        result_dict['motion_smoothness'] = get_motion_smoothness(self.obs_history, self.dt)
        result_dict['min_ped_dist'], result_dict['avg_ped_dist'] = get_min_ped_dist(self.obs_history)
        
        if output:
            self.logger.info("Success: {}".format(result_dict['success']))
            if not result_dict['success']:
                self.logger.info("Fail reason: {}".format(result_dict['fail_reason']))
                
        return result_dict

    def _write_video(self):
        # write the video of the simulation
        anim = animation.ArtistAnimation(self.fig, self.image_sequences, interval=100, blit=True, repeat_delay=1000)
        ax = plt.gca()
        ax.set_aspect(1)
        Writer = animation.writers['ffmpeg']
        writer = Writer(fps=1/self.dt, metadata=dict(artist='Me'), bitrate=1800)

        video_path = os.path.join(self.output_dir,
                                self.env_name + '_' +
                                str(self.env_flag) + '_' +
                                str(self.case_id) + '_' +
                                str(self.start_frame) + '_' +
                                str(self.time) +
                                '.mp4')
        anim.save(video_path, writer=writer)

        self.logger.info("Video saved at {}.".format(video_path))
        return

    def render(self):
        # render the current frame

        curr_frame = []

        curr_frame.append(plt.title("Time frame: {}".format(self.time)))

        curr_frame.append(plt.scatter(self.start_pos[0], self.start_pos[1], c='g', s=10))
        curr_frame.append(plt.scatter(self.robot_path[:, 0], self.robot_path[:, 1], c='y', s=10))
        curr_frame.append(plt.scatter(self.robot_path[-1, 0], self.robot_path[-1, 1], c='blue', s=10))
        curr_frame.append(plt.scatter(self.goal_pos[0], self.goal_pos[1], c='m', s=10))

        # for adding plot follow point, pos and vel in motion_angle, in quiver
        if self.follow_pos is not None:
            curr_frame.append(plt.scatter(self.follow_pos[0], self.follow_pos[1], c='b', s=15))
        pedestrians_pos = np.array(self.pedestrians_pos)
        pedestrians_vel = np.array(self.pedestrians_vel)

        if self.num_ped > 0:
            curr_frame.append(plt.scatter(pedestrians_pos[:, 0], pedestrians_pos[:, 1], c='r', s=25))
            pedestrian_vel_rho = np.linalg.norm(pedestrians_vel, axis=1)
            pedestrian_vel_theta = np.arctan2(pedestrians_vel[:, 1], pedestrians_vel[:, 0])
            u, v = mpc_utils.pol2cart(pedestrian_vel_rho, pedestrian_vel_theta)
            curr_frame.append(plt.quiver(pedestrians_pos[:, 0], pedestrians_pos[:, 1], u, v, color='r', scale=1, scale_units='xy', angles='xy'))

            boundaries = draw_all_social_spaces(self.group_labels,
                                                pedestrians_pos,
                                                pedestrians_vel,
                                                self.group_params['size_const'],
                                                offset=0)

            if len(boundaries) > 0:
                for boundary in boundaries:
                    boundary.append(boundary[0])
                    b = np.array(boundary)
                    group_plt, = plt.plot(b[:, 0], b[:, 1], c='k', linewidth=1)
                    curr_frame.append(group_plt)


        return curr_frame


    def _fading_line(self, xs, ys, color="tab:red", lw=2.5):
        """
        Returns a LineCollection where earlier segments are lighter and later segments darker.
        """
        pts = np.column_stack([xs, ys])
        if len(pts) < 2:
            return None
        segs = np.stack([pts[:-1], pts[1:]], axis=1)               # (T-1, 2, 2)
        alphas = np.linspace(0.2, 1.0, len(segs))                  # fade-in
        lc = LineCollection(segs, colors=[(*plt.matplotlib.colors.to_rgb(color), a) for a in alphas], linewidths=lw, zorder=2)
        return lc


    def render_v2(self):
        # render the current frame

        frame = []

        self.ax.set_title(f"Time frame: {self.time}")
        
        lc = self._fading_line(self.robot_path[:, 0], self.robot_path[:, 1], color="tab:red", lw=5)
        if lc is not None:
            self.ax.add_collection(lc)
            frame.append(lc)
        
        # Robot marker + safety circle
        p_robot = self.ax.scatter(self.robot_path[-1, 0], self.robot_path[-1, 1], marker="D", c="tab:red", s=50, zorder=3)
        frame.append(p_robot)
        circ = Circle((self.robot_path[-1, 0], self.robot_path[-1, 1]), 5, edgecolor='tab:grey',
                    facecolor='none', linestyle='--', linewidth=3, alpha=0.6, zorder=2)
        self.ax.add_patch(circ)
        frame.append(circ)

        # Goal
        p_goal = self.ax.scatter(self.goal_pos[0], self.goal_pos[1], s=70, marker="X", c="tab:green", zorder=3)
        frame.append(p_goal)

        # Follow point
        if self.follow_pos is not None:
            p_follow = self.ax.scatter(self.follow_pos[0], self.follow_pos[1], c='b', s=15, zorder=3)
            frame.append(p_follow)

        # Pedestrians + quivers
        if self.num_ped > 0:
            pos = np.asarray(self.pedestrians_pos)
            vel = np.asarray(self.pedestrians_vel)
            p_peds = self.ax.scatter(pos[:, 0], pos[:, 1], s=30, c="tab:blue", alpha=0.9, zorder=3)
            frame.append(p_peds)

            rho = np.linalg.norm(vel, axis=1)
            th  = np.arctan2(vel[:, 1], vel[:, 0])
            u, v = mpc_utils.pol2cart(rho, th)
            q = self.ax.quiver(pos[:, 0], pos[:, 1], u, v, color='tab:blue',
                            scale=0.5, width=0.005, scale_units='xy', angles='xy', zorder=2)
            frame.append(q)

            boundaries = draw_all_social_spaces(
                self.group_labels,
                pos, vel, self.group_params['size_const'], offset=0)

            for boundary in boundaries or []:
                boundary.append(boundary[0])
                b = np.array(boundary)
                (line,) = self.ax.plot(b[:, 0], b[:, 1], c='k', linewidth=1, zorder=1)
                frame.append(line)

        return frame